# Self-Hosted Github Action Runners on AWS via Cirun.io
# Reference: https://docs.cirun.io/reference/yaml.html
runners:
  - name: gpu-runner
    # Cloud Provider: Amazon Web Services
    cloud: aws
    # NVIDIA GPU
    instance_type: g4dn.xlarge
    # Custom-defined Ubuntu AMI with AMD drivers and build tools pre-installed
    machine_image: ami-04462a876c33e6acf
    region: us-east-2
    preemptible: false
    # Relevant workflow file
    workflow: .github/workflows/test-gpu.yml
    # Provision 1 runner for ubuntu testing for now
    count: 1
    # Add a label to match runs-on param in Github Actions yml files
    labels:
      - gpu
  
  - name: notebook-gpu-runner
    # Cloud Provider: Amazon Web Services
    cloud: aws
    # NVIDIA GPU
    instance_type: g4dn.xlarge
    # Custom-defined Ubuntu AMI with AMD drivers and build tools pre-installed
    machine_image: ami-0328487742df7e739
    region: us-east-2
    preemptible: false
    # Relevant workflow file
    workflow: .github/workflows/test-notebooks.yml
    # Provision 1 runner for ubuntu testing for now
    count: 1
    # Add a label to match runs-on param in Github Actions yml files
    labels:
      - notebook-gpu
