name: clang-format linter

on: [push,pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - uses: InsightSoftwareConsortium/ITKClangFormatLinterAction@bab3a0bb26af8a23c7cc2c1d4265834415089eb5 # main
      with:
        itk-branch: main
